-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 13:42:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NULL AUTO_INCREMENT,
  `cust_lname` VARCHAR(45) NOT NULL,
  `cust_fname` VARCHAR(45) NOT NULL,
  `cust_add` VARCHAR(100) NOT NULL,
  `cust_phone` INT(11) NULL,
  `RESTO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CUSTOMER_RESTO1_idx` (`RESTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_CUSTOMER_RESTO1`
    FOREIGN KEY (`RESTO_id`)
    REFERENCES `mydb`.`resto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NULL AUTO_INCREMENT,
  `emp_lname` VARCHAR(45) NULL DEFAULT NULL,
  `emp_fname` VARCHAR(45) NULL DEFAULT NULL,
  `emp_add` VARCHAR(45) NULL DEFAULT NULL,
  `emp_email` VARCHAR(45) NULL DEFAULT NULL,
  `emp_phone` VARCHAR(45) NULL DEFAULT NULL,
  `emp_type` VARCHAR(45) NULL DEFAULT NULL,
  `RESTO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_EMPLOYEE_RESTO1_idx` (`RESTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_RESTO1`
    FOREIGN KEY (`RESTO_id`)
    REFERENCES `mydb`.`resto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`food` ;

CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `food_name` VARCHAR(45) NULL DEFAULT NULL,
  `food_price` INT NULL DEFAULT NULL,
  `food_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `od_quantity` INT(4) NOT NULL,
  `od_item` VARCHAR(1000) NOT NULL,
  `od_remarks` VARCHAR(1000) NULL,
  `food_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_detail_food1_idx` (`food_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_detail_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `mydb`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_header`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_header` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_header` (
  `id` INT NULL AUTO_INCREMENT,
  `oh_date` DATE NOT NULL,
  `order_stat` VARCHAR(45) NOT NULL,
  `CUSTOMER_id` INT NOT NULL,
  `order_detail_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ORDER_CUSTOMER1_idx` (`CUSTOMER_id` ASC) VISIBLE,
  INDEX `fk_order_header_order_detail1_idx` (`order_detail_id` ASC) VISIBLE,
  CONSTRAINT `fk_ORDER_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_header_order_detail1`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `mydb`.`order_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` INT NULL AUTO_INCREMENT,
  `payment_amount_total` DECIMAL NOT NULL,
  `payment_amount_paid` DECIMAL NULL,
  `payment_tax` DECIMAL NULL,
  `payment_discount` DECIMAL NULL,
  `payment_change` DECIMAL NULL,
  `payment_reference_num` INT NULL,
  `order_header_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_order_header1_idx` (`order_header_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order_header1`
    FOREIGN KEY (`order_header_id`)
    REFERENCES `mydb`.`order_header` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`resto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`resto` (
  `id` INT NULL AUTO_INCREMENT,
  `resto_name` VARCHAR(45) NULL DEFAULT NULL,
  `resto_found_date` DATE NULL DEFAULT NULL,
  `resto_owner` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`supplier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id` INT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(45) NULL DEFAULT NULL,
  `supplier_loc` VARCHAR(45) NULL DEFAULT NULL,
  `partners_num` INT NULL DEFAULT NULL,
  `RESTO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PARTNER_RESTO_idx` (`RESTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_PARTNER_RESTO`
    FOREIGN KEY (`RESTO_id`)
    REFERENCES `mydb`.`resto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
