-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 14:15:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sauce_chef
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sauce_chef
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sauce_chef` ;
-- -----------------------------------------------------
-- Schema suace_
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema suace_
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `suace_` DEFAULT CHARACTER SET utf8 ;
USE `sauce_chef` ;

-- -----------------------------------------------------
-- Table `sauce_chef`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sauce_chef`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingredient_code` VARCHAR(45) NULL,
  `ingredient_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`food` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `food_name` VARCHAR(45) NULL DEFAULT NULL,
  `food_price` INT NULL DEFAULT NULL,
  `food_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sauce_chef`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sauce_chef`.`recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingredients_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  INDEX `fk_ingredients_has_food_food1_idx` (`food_id` ASC) VISIBLE,
  INDEX `fk_ingredients_has_food_ingredients_idx` (`ingredients_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ingredients_has_food_ingredients`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `sauce_chef`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_has_food_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `suace_`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `suace_` ;

-- -----------------------------------------------------
-- Table `suace_`.`resto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`resto` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `resto_name` VARCHAR(45) NULL DEFAULT NULL,
  `resto_found_date` DATE NULL DEFAULT NULL,
  `resto_owner` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`customer` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `cust_lname` VARCHAR(45) NOT NULL,
  `cust_fname` VARCHAR(45) NOT NULL,
  `cust_add` VARCHAR(100) NOT NULL,
  `cust_phone` INT(11) NULL DEFAULT NULL,
  `RESTO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CUSTOMER_RESTO1_idx` (`RESTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_CUSTOMER_RESTO1`
    FOREIGN KEY (`RESTO_id`)
    REFERENCES `suace_`.`resto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`employee` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `emp_lname` VARCHAR(45) NULL DEFAULT NULL,
  `emp_fname` VARCHAR(45) NULL DEFAULT NULL,
  `emp_add` VARCHAR(45) NULL DEFAULT NULL,
  `emp_email` VARCHAR(45) NULL DEFAULT NULL,
  `emp_phone` VARCHAR(45) NULL DEFAULT NULL,
  `emp_type` VARCHAR(45) NULL DEFAULT NULL,
  `RESTO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_EMPLOYEE_RESTO1_idx` (`RESTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_RESTO1`
    FOREIGN KEY (`RESTO_id`)
    REFERENCES `suace_`.`resto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `od_quantity` INT(4) NOT NULL,
  `od_item` VARCHAR(1000) NOT NULL,
  `od_remarks` VARCHAR(1000) NULL DEFAULT NULL,
  `food_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_detail_food1_idx` (`food_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_detail_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `suace_`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`order_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`order_header` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `oh_date` DATE NOT NULL,
  `order_stat` VARCHAR(45) NOT NULL,
  `CUSTOMER_id` INT NOT NULL,
  `order_detail_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ORDER_CUSTOMER1_idx` (`CUSTOMER_id` ASC) VISIBLE,
  INDEX `fk_order_header_order_detail1_idx` (`order_detail_id` ASC) VISIBLE,
  CONSTRAINT `fk_ORDER_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_id`)
    REFERENCES `suace_`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_header_order_detail1`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `suace_`.`order_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`payment` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `payment_amount_total` DECIMAL NOT NULL,
  `payment_amount_paid` DECIMAL NULL DEFAULT NULL,
  `payment_tax` DECIMAL NULL DEFAULT NULL,
  `payment_discount` DECIMAL NULL DEFAULT NULL,
  `payment_change` DECIMAL NULL DEFAULT NULL,
  `payment_reference_num` INT NULL DEFAULT NULL,
  `order_header_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_order_header1_idx` (`order_header_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order_header1`
    FOREIGN KEY (`order_header_id`)
    REFERENCES `suace_`.`order_header` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`supplier` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(45) NULL DEFAULT NULL,
  `supplier_loc` VARCHAR(45) NULL DEFAULT NULL,
  `partners_num` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suace_`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suace_`.`purchase_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `resto_id` INT NOT NULL,
  `po_order_date` DATE NULL,
  `po_delivery_date` DATE NULL,
  `po_order_stat` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_has_resto_resto1_idx` (`resto_id` ASC) VISIBLE,
  INDEX `fk_supplier_has_resto_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_has_resto_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `suace_`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_resto_resto1`
    FOREIGN KEY (`resto_id`)
    REFERENCES `suace_`.`resto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
